name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs every 10 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request
        run: curl -s https://admin-nbrh.onrender.com > /dev/null
